version: "2"
services:
  garage:
    image: ghcr.io/avihaiadler/garage-management-service-postgres:0.0.1
    ports:
      - 8080:8080
    environment:
      POSTGRES_URI: jdbc:postgresql://localhost:5432/postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: on-failure
    expose:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - postgres-volume:/var/lib/postgresql


volumes:
  postgres-volume:
    driver: local